#!/usr/bin/env bash

# Set up autograder files

submitFiles=( "hello_world.py" )

if [[ -z "${JMU_GRADESCOPE_BASE}" ]]; then
  GRADESCOPE_BASE="/autograder"
else
  GRADESCOPE_BASE="${JMU_GRADESCOPE_BASE}"
fi

for t in ${submitFiles[@]}; do
    cp $GRADESCOPE_BASE/submission/$t $GRADESCOPE_BASE/source/$t
done

cd $GRADESCOPE_BASE/source

python3 run_tests.py
